// Explore activities: awe-inspiring things to do, organized by category and time horizon
// Each activity has a unique id for tracking completion

export const EXPLORE_ACTIVITIES = {
  'moral-beauty': {
    label: 'Moral Beauty',
    subtitle: 'Human Goodness',
    color: 'from-rose-400 to-pink-600',
    today: [
      { id: 'mb-t-1', text: 'Write a sincere thank-you message' },
      { id: 'mb-t-2', text: 'Pay for someone anonymously' },
      { id: 'mb-t-3', text: 'Leave a positive review for a small business' },
      { id: 'mb-t-4', text: 'Call someone you haven\'t checked on' },
      { id: 'mb-t-5', text: 'Offer help without being asked' },
      { id: 'mb-t-6', text: 'Apologize genuinely' },
      { id: 'mb-t-7', text: 'Donate a small amount quietly' },
      { id: 'mb-t-8', text: 'Compliment someone meaningfully' },
      { id: 'mb-t-9', text: 'Help a stranger briefly' },
      { id: 'mb-t-10', text: 'Reflect on someone who shaped your life' },
    ],
    month: [
      { id: 'mb-m-1', text: 'Volunteer at a shelter' },
      { id: 'mb-m-2', text: 'Mentor someone younger' },
      { id: 'mb-m-3', text: 'Join a community cleanup' },
      { id: 'mb-m-4', text: 'Donate blood' },
      { id: 'mb-m-5', text: 'Serve food at a local kitchen' },
      { id: 'mb-m-6', text: 'Support a grassroots cause' },
    ],
    lifetime: [
      { id: 'mb-l-1', text: 'Commit long-term to a volunteer mission' },
      { id: 'mb-l-2', text: 'Sponsor someone\'s education' },
      { id: 'mb-l-3', text: 'Participate in humanitarian rebuilding' },
    ],
  },
  'collective-effervescence': {
    label: 'Collective Effervescence',
    subtitle: 'Shared Energy',
    color: 'from-orange-400 to-red-600',
    today: [
      { id: 'ce-t-1', text: 'Attend a sports game' },
      { id: 'ce-t-2', text: 'Join a group fitness class' },
      { id: 'ce-t-3', text: 'Visit a public gathering' },
      { id: 'ce-t-4', text: 'Sit in a crowded plaza' },
      { id: 'ce-t-5', text: 'Attend a local ceremony' },
      { id: 'ce-t-6', text: 'Join a public rally peacefully' },
      { id: 'ce-t-7', text: 'Participate in group meditation' },
      { id: 'ce-t-8', text: 'Attend a wedding' },
      { id: 'ce-t-9', text: 'Join a choir practice' },
      { id: 'ce-t-10', text: 'Watch fireworks with others' },
    ],
    month: [
      { id: 'ce-m-1', text: 'Attend a music festival' },
      { id: 'ce-m-2', text: 'Participate in a cultural festival' },
      { id: 'ce-m-3', text: 'Join a group pilgrimage' },
      { id: 'ce-m-4', text: 'Attend a major sporting event' },
      { id: 'ce-m-5', text: 'Join a marathon event' },
      { id: 'ce-m-6', text: 'Attend a public holiday celebration' },
    ],
    lifetime: [
      { id: 'ce-l-1', text: 'Experience Carnival or Holi' },
      { id: 'ce-l-2', text: 'Attend the World Cup final' },
      { id: 'ce-l-3', text: 'Participate in a historic national ceremony' },
    ],
  },
  nature: {
    label: 'Nature',
    subtitle: 'The Natural World',
    color: 'from-green-400 to-emerald-600',
    today: [
      { id: 'na-t-1', text: 'Watch sunrise' },
      { id: 'na-t-2', text: 'Watch sunset' },
      { id: 'na-t-3', text: 'Sit under a tree' },
      { id: 'na-t-4', text: 'Visit a park' },
      { id: 'na-t-5', text: 'Observe birds' },
      { id: 'na-t-6', text: 'Lie down and watch clouds' },
      { id: 'na-t-7', text: 'Walk by water' },
      { id: 'na-t-8', text: 'Look at the moon' },
      { id: 'na-t-9', text: 'Smell flowers intentionally' },
      { id: 'na-t-10', text: 'Listen to rain' },
    ],
    month: [
      { id: 'na-m-1', text: 'Weekend hike' },
      { id: 'na-m-2', text: 'Camping trip' },
      { id: 'na-m-3', text: 'National park visit' },
      { id: 'na-m-4', text: 'Stargazing trip' },
      { id: 'na-m-5', text: 'Botanical garden visit' },
      { id: 'na-m-6', text: 'Ocean day trip' },
    ],
    lifetime: [
      { id: 'na-l-1', text: 'See Northern Lights' },
      { id: 'na-l-2', text: 'Visit Grand Canyon or equivalent' },
      { id: 'na-l-3', text: 'Trek to a high-altitude peak' },
    ],
  },
  'visual-design': {
    label: 'Visual Design',
    subtitle: 'Art & Beauty',
    color: 'from-blue-400 to-cyan-600',
    today: [
      { id: 'vd-t-1', text: 'Visit a gallery' },
      { id: 'vd-t-2', text: 'Sketch for 20 minutes' },
      { id: 'vd-t-3', text: 'Photograph textures' },
      { id: 'vd-t-4', text: 'Rearrange your room visually' },
      { id: 'vd-t-5', text: 'Study architecture details' },
      { id: 'vd-t-6', text: 'Visit a bookstore art section' },
      { id: 'vd-t-7', text: 'Watch a dance rehearsal' },
      { id: 'vd-t-8', text: 'Observe street art' },
      { id: 'vd-t-9', text: 'Design something minimal' },
      { id: 'vd-t-10', text: 'Visit a design museum online' },
    ],
    month: [
      { id: 'vd-m-1', text: 'Take an art class' },
      { id: 'vd-m-2', text: 'Attend a major exhibition' },
      { id: 'vd-m-3', text: 'Visit a historic architecture site' },
      { id: 'vd-m-4', text: 'Attend a design workshop' },
      { id: 'vd-m-5', text: 'Explore a new neighborhood visually' },
      { id: 'vd-m-6', text: 'Try pottery or ceramics' },
    ],
    lifetime: [
      { id: 'vd-l-1', text: 'Visit the Louvre or a major art museum' },
      { id: 'vd-l-2', text: 'See the Sistine Chapel' },
      { id: 'vd-l-3', text: 'Attend Venice Biennale' },
    ],
  },
  epiphany: {
    label: 'Epiphany',
    subtitle: 'Big Ideas & Insight',
    color: 'from-indigo-400 to-blue-600',
    today: [
      { id: 'ep-t-1', text: 'Watch a TED talk' },
      { id: 'ep-t-2', text: 'Read a philosophy essay' },
      { id: 'ep-t-3', text: 'Visit a science museum' },
      { id: 'ep-t-4', text: 'Listen to a deep podcast' },
      { id: 'ep-t-5', text: 'Study the night sky' },
      { id: 'ep-t-6', text: 'Learn a new concept' },
      { id: 'ep-t-7', text: 'Reflect on time and scale' },
      { id: 'ep-t-8', text: 'Watch a documentary' },
      { id: 'ep-t-9', text: 'Write down one insight' },
      { id: 'ep-t-10', text: 'Visit a university campus' },
    ],
    month: [
      { id: 'ep-m-1', text: 'Attend a public lecture' },
      { id: 'ep-m-2', text: 'Take an online course' },
      { id: 'ep-m-3', text: 'Visit historical ruins' },
      { id: 'ep-m-4', text: 'Join a book discussion' },
      { id: 'ep-m-5', text: 'Attend a science fair' },
      { id: 'ep-m-6', text: 'Debate ideas respectfully' },
    ],
    lifetime: [
      { id: 'ep-l-1', text: 'Visit CERN or NASA center' },
      { id: 'ep-l-2', text: 'See ancient pyramids' },
      { id: 'ep-l-3', text: 'Study under a master teacher' },
    ],
  },
  'life-death': {
    label: 'Life & Death',
    subtitle: 'Preciousness of Life',
    color: 'from-slate-400 to-gray-600',
    today: [
      { id: 'ld-t-1', text: 'Visit a cemetery quietly' },
      { id: 'ld-t-2', text: 'Reflect on your ancestry' },
      { id: 'ld-t-3', text: 'Write a gratitude letter' },
      { id: 'ld-t-4', text: 'Plant a tree' },
      { id: 'ld-t-5', text: 'Reflect on mortality' },
      { id: 'ld-t-6', text: 'Spend time with a newborn' },
      { id: 'ld-t-7', text: 'Visit hospital volunteer desk' },
      { id: 'ld-t-8', text: 'Watch seasonal change' },
      { id: 'ld-t-9', text: 'Write a legacy note' },
      { id: 'ld-t-10', text: 'Call parents or elders' },
    ],
    month: [
      { id: 'ld-m-1', text: 'Participate in a memorial event' },
      { id: 'ld-m-2', text: 'Visit ancestral homeland' },
      { id: 'ld-m-3', text: 'Attend a seasonal ritual' },
      { id: 'ld-m-4', text: 'Volunteer for hospice support' },
      { id: 'ld-m-5', text: 'Document family stories' },
      { id: 'ld-m-6', text: 'Participate in a harvest festival' },
    ],
    lifetime: [
      { id: 'ld-l-1', text: 'Sit with someone at end-of-life' },
      { id: 'ld-l-2', text: 'Witness childbirth' },
      { id: 'ld-l-3', text: 'Participate in Day of the Dead in Mexico' },
    ],
  },
  spirituality: {
    label: 'Spirituality',
    subtitle: 'The Sacred & Transcendent',
    color: 'from-amber-400 to-yellow-600',
    today: [
      { id: 'sp-t-1', text: 'Meditate for 15 minutes' },
      { id: 'sp-t-2', text: 'Sit in silence' },
      { id: 'sp-t-3', text: 'Light a candle' },
      { id: 'sp-t-4', text: 'Visit a temple' },
      { id: 'sp-t-5', text: 'Walk barefoot outdoors' },
      { id: 'sp-t-6', text: 'Practice gratitude prayer' },
      { id: 'sp-t-7', text: 'Read a sacred text passage' },
      { id: 'sp-t-8', text: 'Attend a short service' },
      { id: 'sp-t-9', text: 'Practice breathwork' },
      { id: 'sp-t-10', text: 'Observe stillness at dawn' },
    ],
    month: [
      { id: 'sp-m-1', text: 'Attend a retreat day' },
      { id: 'sp-m-2', text: 'Join a meditation group' },
      { id: 'sp-m-3', text: 'Spend a day offline' },
      { id: 'sp-m-4', text: 'Walk a pilgrimage route locally' },
      { id: 'sp-m-5', text: 'Visit a monastery' },
      { id: 'sp-m-6', text: 'Try a yoga workshop' },
    ],
    lifetime: [
      { id: 'sp-l-1', text: 'Complete the Camino de Santiago' },
      { id: 'sp-l-2', text: 'Spend a week in a monastery' },
      { id: 'sp-l-3', text: 'Visit a sacred mountain' },
    ],
  },
  music: {
    label: 'Music',
    subtitle: 'Sound & Emotion',
    color: 'from-purple-400 to-violet-600',
    today: [
      { id: 'mu-t-1', text: 'Listen to a symphony fully' },
      { id: 'mu-t-2', text: 'Attend a local live performance' },
      { id: 'mu-t-3', text: 'Sing aloud' },
      { id: 'mu-t-4', text: 'Play an instrument briefly' },
      { id: 'mu-t-5', text: 'Listen with eyes closed' },
      { id: 'mu-t-6', text: 'Watch an orchestra rehearsal' },
      { id: 'mu-t-7', text: 'Discover a new genre' },
      { id: 'mu-t-8', text: 'Listen to cultural music' },
      { id: 'mu-t-9', text: 'Attend a street performance' },
      { id: 'mu-t-10', text: 'Share a song with a friend' },
    ],
    month: [
      { id: 'mu-m-1', text: 'Attend a major concert' },
      { id: 'mu-m-2', text: 'Join a choir' },
      { id: 'mu-m-3', text: 'Take music lessons' },
      { id: 'mu-m-4', text: 'Attend an opera' },
      { id: 'mu-m-5', text: 'Attend a cultural music festival' },
      { id: 'mu-m-6', text: 'Visit a music museum' },
    ],
    lifetime: [
      { id: 'mu-l-1', text: 'Attend a world-class orchestra live' },
      { id: 'mu-l-2', text: 'Experience sacred chant in origin culture' },
      { id: 'mu-l-3', text: 'Participate in a global music festival' },
    ],
  },
}

// Time horizon metadata
export const TIME_HORIZONS = {
  today: { key: 'today', label: 'Today', emoji: '🌱', description: 'Small steps you can take right now' },
  month: { key: 'month', label: 'This Month', emoji: '🌤', description: 'Experiences to plan for soon' },
  lifetime: { key: 'lifetime', label: 'Lifetime', emoji: '🌌', description: 'Once-in-a-lifetime adventures' },
}

// Category order for display
export const EXPLORE_CATEGORY_ORDER = [
  'moral-beauty',
  'collective-effervescence',
  'nature',
  'visual-design',
  'epiphany',
  'life-death',
  'spirituality',
  'music',
]
